#!/bin/bash

echo

export FABRIC_CA_CLIENT_HOME=/organizations/peerOrganizations/org1.example.com/
echo $FABRIC_CA_CLIENT_HOME

set -x
fabric-ca-client reenroll -u https://admin:adminpw@ca-org1:8054 --caname ca-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

# Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

# Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
mkdir -p /organizations/peerOrganizations/org1.example.com/msp/tlscacerts
cp /organizations/fabric-ca/org1/ca-cert.pem /organizations/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt

# Copy org1's CA cert to org1's /tlsca directory (for use by clients)
mkdir -p /organizations/peerOrganizations/org1.example.com/tlsca
cp /organizations/fabric-ca/org1/ca-cert.pem /organizations/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

# Copy org1's CA cert to org1's /ca directory (for use by clients)
mkdir -p /organizations/peerOrganizations/org1.example.com/ca
cp /organizations/fabric-ca/org1/ca-cert.pem /organizations/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem

# ---------------------------------------
# peer0

echo "Re-enroll the peer0 MSP"
set -x
fabric-ca-client reenroll -u https://peer0:peer0pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp" --csr.hosts peer0.org1.example.com --csr.hosts  peer0-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/config.yaml"

echo "Re-enroll the peer0 tls certificates"
set -x
fabric-ca-client reenroll -u https://peer0:peer0pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer0.org1.example.com --csr.hosts  peer0-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key

# ---------------------------------------
# peer1

echo "Re-enroll the peer1 MSP"
set -x
fabric-ca-client reenroll -u https://peer1:peer1pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp" --csr.hosts peer1.org1.example.com --csr.hosts  peer1-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/config.yaml"

echo "Re-enroll the peer1 tls certificates"
set -x
fabric-ca-client reenroll -u https://peer1:peer1pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer1.org1.example.com --csr.hosts  peer1-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key

# ---------------------------------------
# peer2

echo "Re-enroll the peer2 MSP"
set -x
fabric-ca-client reenroll -u https://peer2:peer2pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp" --csr.hosts peer2.org1.example.com --csr.hosts  peer2-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp/config.yaml"

echo "Re-enroll the peer2 tls certificates"
set -x
fabric-ca-client reenroll -u https://peer2:peer2pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer2.org1.example.com --csr.hosts  peer2-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/server.key

# ---------------------------------------
# peer3

echo "Re-enroll the peer3 MSP"
set -x
fabric-ca-client reenroll -u https://peer3:peer3pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp" --csr.hosts peer3.org1.example.com --csr.hosts  peer3-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp/config.yaml"

echo "Re-enroll the peer3 tls certificates"
set -x
fabric-ca-client reenroll -u https://peer3:peer3pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer3.org1.example.com --csr.hosts  peer3-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/server.key

# ---------------------------------------

echo "Re-enroll the user MSP"
set -x
fabric-ca-client reenroll -u https://user1:user1pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp" --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/config.yaml"


echo "Re-enroll the admin MSP"
set -x
fabric-ca-client reenroll -u https://org1admin:org1adminpw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem" --csr.keyrequest.reusekey
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/config.yaml"