#!/bin/bash

echo
mkdir -p /organizations/peerOrganizations/org1.example.com/

export FABRIC_CA_CLIENT_HOME=/organizations/peerOrganizations/org1.example.com/
echo $FABRIC_CA_CLIENT_HOME

set -x
fabric-ca-client enroll -u https://admin:adminpw@ca-org1:8054 --caname ca-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org1.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org1.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org1.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-org1.pem
    OrganizationalUnitIdentifier: orderer' > "/organizations/peerOrganizations/org1.example.com/msp/config.yaml"

# Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

# Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
mkdir -p /organizations/peerOrganizations/org1.example.com/msp/tlscacerts
cp /organizations/fabric-ca/org1/ca-cert.pem /organizations/peerOrganizations/org1.example.com/msp/tlscacerts/ca.crt

# Copy org1's CA cert to org1's /tlsca directory (for use by clients)
mkdir -p /organizations/peerOrganizations/org1.example.com/tlsca
cp /organizations/fabric-ca/org1/ca-cert.pem /organizations/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem

# Copy org1's CA cert to org1's /ca directory (for use by clients)
mkdir -p /organizations/peerOrganizations/org1.example.com/ca
cp /organizations/fabric-ca/org1/ca-cert.pem /organizations/peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem

echo "Generate user identity"
set -x
fabric-ca-client register --caname ca-org1 --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

echo "Generate org1 admin identity"
set -x
fabric-ca-client register --caname ca-org1 --id.name org1admin --id.secret org1adminpw --id.type admin --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

# -------------------------------
echo "Register peer0"
set -x
fabric-ca-client register --caname ca-org1 --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

echo "Register peer1"
set -x
fabric-ca-client register --caname ca-org1 --id.name peer1 --id.secret peer1pw --id.type peer --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

echo "Register peer2"
set -x
fabric-ca-client register --caname ca-org1 --id.name peer2 --id.secret peer2pw --id.type peer --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

echo "Register peer3"
set -x
fabric-ca-client register --caname ca-org1 --id.name peer3 --id.secret peer3pw --id.type peer --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

# ---------------------------------------
# peer0

echo "Generate the peer0 MSP"
set -x
fabric-ca-client enroll -u https://peer0:peer0pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp" --csr.hosts peer0.org1.example.com --csr.hosts  peer0-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/config.yaml"

echo "Generate peer0 tls certificates"
set -x
fabric-ca-client enroll -u https://peer0:peer0pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer0.org1.example.com --csr.hosts  peer0-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key

# ---------------------------------------
# peer1

echo "Generate the peer1 MSP"
set -x
fabric-ca-client enroll -u https://peer1:peer1pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp" --csr.hosts peer1.org1.example.com --csr.hosts  peer1-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp/config.yaml"

echo "Generate peer1 tls certificates"
set -x
fabric-ca-client enroll -u https://peer1:peer1pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer1.org1.example.com --csr.hosts  peer1-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.key

# ---------------------------------------
# peer2

echo "Generate the peer2 MSP"
set -x
fabric-ca-client enroll -u https://peer2:peer2pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp" --csr.hosts peer2.org1.example.com --csr.hosts  peer2-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/msp/config.yaml"

echo "Generate peer2 tls certificates"
set -x
fabric-ca-client enroll -u https://peer2:peer2pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer2.org1.example.com --csr.hosts  peer2-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer2.org1.example.com/tls/server.key

# ---------------------------------------
# peer3

echo "Generate the peer3 MSP"
set -x
fabric-ca-client enroll -u https://peer3:peer3pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp" --csr.hosts peer3.org1.example.com --csr.hosts  peer3-org1 --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/msp/config.yaml"

echo "Generate peer3 tls certificates"
set -x
fabric-ca-client enroll -u https://peer3:peer3pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls" --enrollment.profile tls --csr.hosts peer3.org1.example.com --csr.hosts  peer3-org1 --csr.hosts ca-org1 --csr.hosts localhost --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

# Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
cp /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/tlscacerts/* /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/ca.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/signcerts/* /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/server.crt
cp /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/keystore/* /organizations/peerOrganizations/org1.example.com/peers/peer3.org1.example.com/tls/server.key

# ---------------------------------------

echo "Generate user MSP"
set -x
fabric-ca-client enroll -u https://user1:user1pw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp" --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/config.yaml"


echo "Generate admin MSP"
set -x
fabric-ca-client enroll -u https://org1admin:org1adminpw@ca-org1:8054 --caname ca-org1 -M "/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp" --tls.certfiles "/organizations/fabric-ca/org1/tls-cert.pem"
{ set +x; } 2>/dev/null

cp "/organizations/peerOrganizations/org1.example.com/msp/config.yaml" "/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/config.yaml"