apiVersion: batch/v1
kind: Job
metadata:
  name: ccp-generate-job
spec:
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      restartPolicy: Never
      volumes:
        - name: fabric-nfs
          persistentVolumeClaim:
            claimName: fabric-pvc-nfs
      containers:
        - name: ccp-generate
          image: hyperledger/fabric-tools:2.3
          workingDir: /
          volumeMounts:
            - mountPath: /scripts
              name: fabric-nfs
              subPath: scripts
            - mountPath: /connection-profile
              name: fabric-nfs
              subPath: connection-profile
            - mountPath: /organizations
              name: fabric-nfs
              subPath: organizations
          command:
            - /bin/bash
            - -c
            - |
              ./scripts/ccp-generate.sh