apiVersion: batch/v1
kind: Job
metadata:
  name: register-enroll-certs
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: register-enroll-certs
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: fabric-pvc-nfs
      containers:
        - name: register-enroll-certs
          image: hyperledger/fabric-ca-tools:1.2.1
          resources:
            requests:
              memory: 300Mi
              cpu: 200m
            limits:
              memory: 400Mi
              cpu: 250m
          volumeMounts:
            - mountPath: /organizations
              name: fabricfiles
              subPath: organizations
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/orderer-certs.sh &&
              ./scripts/org1-certs.sh
      restartPolicy: Never