apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-pvc-worker2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  volumeName: fabric-pv-worker2  # Ensures binding to that exact PV matching metadata name
