apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-pvc-worker1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  volumeName: fabric-pv-worker1  # Ensures binding to that exact PV matching metadata name
