apiVersion: v1
kind: Service
metadata:
  name: node-chaincode
  # metadata name should match with address value in connection.json chaincode pkg folder
  labels:
    app: node-chaincode
spec:
  ports:
    - name: grpc
      port: 7053
      targetPort: 7053
  selector:
    app: chaincode-node
