apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaincode-node-deploy
  labels:
    app: chaincode-node
spec:
  selector:
    matchLabels:
      app: chaincode-node
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-node
    spec:
      containers:
        - image: vikashftw/product-contract-node:1.0
          imagePullPolicy: Always
          name: chaincode-node
          env:
            - name: CORE_CHAINCODE_ID
              value: smartcontract-node:<CC_deployment_token>
            - name: CORE_CHAINCODE_ADDRESS
              value: "0.0.0.0:7053"
            - name: CHAINCODE_NAME
              value: smartcontract-node
          ports:
            - containerPort: 7053