apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: orderer3
spec:
    serviceName: "orderer3"
    selector:
        matchLabels:
            name: orderer3
    replicas: 1
    template:
        metadata:
            labels:
                name: orderer3
        spec:
           affinity:
             nodeAffinity:
               requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - worker2

           initContainers:
             - name: sync-from-nfs
               image: busybox:latest
               command:
                 - sh
                 - -c
                 - |
                   set -e
                   # 1. Verify NFS is actually mounted and reachable
                   if [ ! -d /nfs-mount/organizations ] || [! -d /nfs-mount/system-genesis-block] || [! -d /nfs-mount/channel-artifacts]; then
                     echo "ERROR: NFS source not found OR `organizations, system-genesis-block, channel-artifacts` folder not exist.. Therefore cannot sync !!"
                     exit 1
                   fi
                   # 2. Check if the folder is already on local disk and NOT empty
                   if [ -d /local-mount/organizations ] && [ "$(ls -A /local-mount/organizations)" ]; then
                     echo "Found existing crypto data on local disk. Skipping sync to save I/O."
                   else
                     echo "Shared disk is empty or missing data. Starting Bulk Sync from NFS..."
                     mkdir -p /local-mount/organizations
                     mkdir -p /local-mount/system-genesis-block
                     mkdir -p /local-mount/channel-artifacts
                     cp -af /nfs-mount/organizations/* /local-mount/organizations/
                     cp -af /nfs-mount/system-genesis-block/* /local-mount/system-genesis-block/
                     cp -af /nfs-mount/channel-artifacts/* /local-mount/channel-artifacts/
                     echo "--- Sync complete. ---"
                   fi
                   
               volumeMounts:
                - name: fabric-nfs
                  mountPath: /nfs-mount
                - name: fabric-local
                  mountPath: /local-mount

           volumes:
             - name: fabric-nfs
               persistentVolumeClaim:
                  claimName: fabric-pvc-nfs
             - name: fabric-local
               persistentVolumeClaim:
                  claimName: fabric-pvc-worker2

           containers:
             - image: hyperledger/fabric-orderer:2.3
               name: orderer3
               imagePullPolicy: IfNotPresent
               env:
                - name: CONFIGTX_ORDERER_ADDRESSES
                  value: "orderer3:7050"
                - name: ORDERER_GENERAL_LISTENADDRESS
                  value: "0.0.0.0"
                - name: ORDERER_GENERAL_LISTENPORT
                  value: "7050"
                - name: ORDERER_GENERAL_LOGLEVEL
                  value: debug
                - name: ORDERER_GENERAL_LOCALMSPDIR
                  value: /organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/msp
                - name: ORDERER_GENERAL_LOCALMSPID
                  value: OrdererMSP
                - name: ORDERER_GENERAL_GENESISMETHOD
                  value: file
                - name: ORDERER_GENERAL_GENESISFILE
                  value: /system-genesis-block/genesis.block
                - name: ORDERER_GENERAL_TLS_ENABLED
                  value: "true"
                - name: ORDERER_GENERAL_TLS_PRIVATEKEY
                  value: /organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.key
                - name: ORDERER_GENERAL_TLS_CERTIFICATE
                  value: /organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
                - name: ORDERER_GENERAL_TLS_ROOTCAS
                  value: /organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/ca.crt
                - name:  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
                  value: /organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.key
                - name:  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
                  value: /organizations/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt

               volumeMounts:
                - mountPath: /organizations
                  name: fabric-local
                  subPath: organizations

                - mountPath: /system-genesis-block
                  name: fabric-local
                  subPath: system-genesis-block

                - mountPath: /var/hyperledger/production
                  name: fabric-local
                  subPath: orderer-data/orderer3