kind: Service
apiVersion: v1
metadata:
    name: orderer5
    labels:
        run: orderer5
spec:
    selector:
        name: orderer5
    type: ClusterIP
    ports:
        - protocol: TCP
          port: 7050
          name: grpc
---
#---------------- Orderer Metrics Service ---------------
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer5
    component: orderer
    metrics-service: "true"
  name: orderer5-metrics
spec:
  type: ClusterIP
  ports:
  - name: "orderer-metrics"
    port: 9435
    targetPort: 9435
  selector:
    name: orderer5
