apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-db
  labels:
    app: explorer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorerdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: explorerdb
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker2

      securityContext:
        fsGroup: 999

      volumes:
        - name: fabric-local
          persistentVolumeClaim:
            claimName: fabric-pvc-worker2

      containers:
        - name: hyperledger-explorerdb
          image: ghcr.io/hyperledger-labs/explorer-db:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: explorer-db-secret
                  key: DATABASE_DATABASE
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: explorer-db-secret
                  key: DATABASE_USERNAME
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: explorer-db-secret
                  key: DATABASE_PASSWORD
          volumeMounts:
            - name: fabric-local
              mountPath: /var/lib/postgresql/data
              subPath: explorer-pgdata

          # healthcheck
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
                - -q
                - -U
                - postgres
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
                - -q
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"