apiVersion: v1
kind: Service
metadata:
  name: explorerdb-svc
  labels:
    app: explorerdb
spec:
  type: ClusterIP
  selector:
    app: explorerdb
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432