apiVersion: v1
kind: Service
metadata:
  name: ca-orderer
  labels:
    app: ca-orderer
spec:
  type: ClusterIP 
  ports:
    - protocol: TCP
      targetPort: 7054
      port: 7054
  selector:
    app: ca-orderer