apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-orderer
spec:
  selector:
    matchLabels:
      app: ca-orderer
  replicas: 1
  template:
    metadata:
      labels:
        app: ca-orderer
    spec:
      volumes:
        - name: fabric-nfs
          persistentVolumeClaim:
            claimName: fabric-pvc-nfs

      containers:
        - name: ca-orderer
          image: hyperledger/fabric-ca:1.5.11
          imagePullPolicy: IfNotPresent
          command:
            [
              "fabric-ca-server" ,
              "start", "-b" ,"admin:adminpw", "-d"
            ]
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 500Mi
              cpu: 350m
          env:
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-orderer
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_PORT
              value: "7054"
            - name: FABRIC_CA_SERVER_CSR_CN
              value: "ca-orderer"
            - name: FABRIC_CA_SERVER_CSR_HOSTS
              value: "ca-orderer,example.com,localhost"
            - name: FABRIC_CA_SERVER_CA_REENROLLIGNORECERTEXPIRY
              value: "true"
          volumeMounts:
            - name: fabric-nfs
              mountPath: /etc/hyperledger/fabric-ca-server
              subPath: organizations/fabric-ca/ordererOrg