apiVersion: v1
kind: Service
metadata:
  name: ca-org1
  labels:
    app: ca-org1
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 8054
      port: 8054
  selector:
    app: ca-org1