apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-chaincode-go
  labels:
    app: external-chaincode-go
    component: smart-contract
    
spec:
  selector:
    matchLabels:
      app: chaincode-go
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-go
    spec:
      containers:
        - image: vikashftw/product-contract-go:1.0
          imagePullPolicy: Always
          name: chaincode-go
          env:
            - name: CHAINCODE_ID
              value: smartcontract-go:<CC_deployment_token>
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
            - name: CHAINCODE_NAME
              value: smartcontract-go
          ports:
            - containerPort: 7052