apiVersion: v1
kind: Service
metadata:
  name: go-chaincode 
  # metadata name should match with address value in connection.json chaincode pkg folder
  labels:
    app: go-chaincode
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-go
