apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chaincode-deploy
  labels:
    app: go-chaincode-deploy
spec:
  selector:
    matchLabels:
      app: go-chaincode-deploy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-chaincode-deploy
    spec:
      containers:
        - image: vikashftw/product-contract-go:1.0
          imagePullPolicy: Always
          name: go-chaincode-deploy
          env:
            - name: CHAINCODE_ID
              value: <label>:<CC_deployment_token>
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
            - name: CHAINCODE_NAME
              value: fabric-smartcontract-go
          ports:
            - containerPort: 7052