apiVersion: v1
kind: Service
metadata:
  name: chaincode-org1 
  # metadata name should match with address value in connection.json chaincode pkg folder
  labels:
    app: chaincode-org1
spec:
  ports:
    - name: grpc
      port: 7052
      targetPort: 7052
  selector:
    app: chaincode-deploy-org1
