apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-pv-nfs
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/shared_NFS
    server: <NFS NODE IP>